TASK_SCHED_OBJS = 	output/myOS/kernel/task_sched/task_fifo.o \
					output/myOS/kernel/task_sched/task_fmq.o \
					output/myOS/kernel/task_sched/task_prio.o \
					output/myOS/kernel/task_sched/task_prio0.o \
					output/myOS/kernel/task_sched/task_sjf.o