include $(SRC_RT)/myOS/kernel/mem/Makefile
include $(SRC_RT)/myOS/kernel/task_sched/Makefile

KERNEL_OBJS = 	output/myOS/kernel/tick.o \
	      		output/myOS/kernel/wallClock.o \
		  		output/myOS/kernel/task.o \
				output/myOS/kernel/task_arr.o \
				output/myOS/kernel/taskPara.o \
				output/myOS/kernel/task_sched.o \
	      		$(MEM_OBJS) ${TASK_SCHED_OBJS}
